// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCarLocation = "car_locations"

// CarLocation mapped from table <car_locations>
type CarLocation struct {
	ID              int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SpecificAddress string    `gorm:"column:specific_address;not null" json:"specific_address"`
	Ward            string    `gorm:"column:ward;not null" json:"ward"`
	District        string    `gorm:"column:district;not null" json:"district"`
	Province        string    `gorm:"column:province;not null" json:"province"`
	CarID           int32     `gorm:"column:car_id" json:"car_id"`
	CreatedAt       time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName CarLocation's table name
func (*CarLocation) TableName() string {
	return TableNameCarLocation
}
