// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCarFeatureMapping = "car_feature_mapping"

// CarFeatureMapping mapped from table <car_feature_mapping>
type CarFeatureMapping struct {
	CarID     int32 `gorm:"column:car_id;primaryKey" json:"car_id"`
	FeatureID int32 `gorm:"column:feature_id;primaryKey" json:"feature_id"`
}

// TableName CarFeatureMapping's table name
func (*CarFeatureMapping) TableName() string {
	return TableNameCarFeatureMapping
}
