// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCar = "cars"

// Car mapped from table <cars>
type Car struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Year       int32          `gorm:"column:year;not null" json:"year"`
	UserID     string         `gorm:"column:user_id" json:"user_id"`
	ModelID    int32          `gorm:"column:model_id" json:"model_id"`
	BrandID    int32          `gorm:"column:brand_id" json:"brand_id"`
	FuelID     int32          `gorm:"column:fuel_id" json:"fuel_id"`
	CarDriveID int32          `gorm:"column:car_drive_id" json:"car_drive_id"`
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Car's table name
func (*Car) TableName() string {
	return TableNameCar
}
