// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameDemand = "demands"

// Demand mapped from table <demands>
type Demand struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CarID      int32          `gorm:"column:car_id" json:"car_id"`
	DemandType string         `gorm:"column:demand_type;not null" json:"demand_type"`
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Demand's table name
func (*Demand) TableName() string {
	return TableNameDemand
}
