// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGift = "gifts"

// Gift mapped from table <gifts>
type Gift struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      string         `gorm:"column:user_id" json:"user_id"`
	Name        string         `gorm:"column:name;not null" json:"name"`
	Description string         `gorm:"column:description" json:"description"`
	Image       string         `gorm:"column:image;not null" json:"image"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Gift's table name
func (*Gift) TableName() string {
	return TableNameGift
}
