// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"server-book-ecommerce-gin/internal/constant"
	"time"

	"gorm.io/gorm"
)

const TableNameImage = constant.ImageTable

// Image mapped from table <images>
type Image struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProductID int32          `gorm:"column:product_id;not null" json:"product_id"`
	ImageURL  string         `gorm:"column:image_url;not null" json:"image_url"`
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Image's table name
func (*Image) TableName() string {
	return TableNameImage
}
