// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"server-book-ecommerce-gin/internal/constant"
	"time"
)

const TableNameInvalidatedToken = constant.InvalidateTokenTable

// InvalidatedToken mapped from table <invalidated_tokens>
type InvalidatedToken struct {
	TokenID string    `gorm:"column:token_id;primaryKey" json:"token_id"`
	Expired time.Time `gorm:"column:expired" json:"expired"`
}

// TableName InvalidatedToken's table name
func (*InvalidatedToken) TableName() string {
	return TableNameInvalidatedToken
}
