// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"server-book-ecommerce-gin/internal/constant"
	"time"

	"gorm.io/gorm"
)

const TableNamePolicy = constant.PolicyTable

// Policy mapped from table <policies>
type Policy struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title     string         `gorm:"column:title;not null" json:"title"`
	Content   string         `gorm:"column:content" json:"content"`
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Policy's table name
func (*Policy) TableName() string {
	return TableNamePolicy
}
