// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePromotionOrderItem = "promotion_order_items"

// PromotionOrderItem mapped from table <promotion_order_items>
type PromotionOrderItem struct {
	ID          int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PromotionID int32 `gorm:"column:promotion_id;not null" json:"promotion_id"`
	OrderItemID int64 `gorm:"column:order_item_id;not null" json:"order_item_id"`
}

// TableName PromotionOrderItem's table name
func (*PromotionOrderItem) TableName() string {
	return TableNamePromotionOrderItem
}
