// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRefreshToken = "refresh_tokens"

// RefreshToken mapped from table <refresh_tokens>
type RefreshToken struct {
	TokenID string    `gorm:"column:token_id;primaryKey" json:"token_id"`
	Expired time.Time `gorm:"column:expired" json:"expired"`
	UserID  int64     `gorm:"column:user_id;not null" json:"user_id"`
}

// TableName RefreshToken's table name
func (*RefreshToken) TableName() string {
	return TableNameRefreshToken
}
