// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"server-book-ecommerce-gin/internal/constant"
	"time"

	"gorm.io/gorm"
)

const TableNameSupportCustomer = constant.SupportCustomerTable

// SupportCustomer mapped from table <support_customers>
type SupportCustomer struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email     string         `gorm:"column:email;not null" json:"email"`
	Title     string         `gorm:"column:title;not null" json:"title"`
	Message   string         `gorm:"column:message" json:"message"`
	Feedback  string         `gorm:"column:feedback" json:"feedback"`
	IsSolve   bool           `gorm:"column:is_solve" json:"is_solve"`
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName SupportCustomer's table name
func (*SupportCustomer) TableName() string {
	return TableNameSupportCustomer
}
