// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTrend = "trends"

// Trend mapped from table <trends>
type Trend struct {
	ID        int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CarID     int32          `gorm:"column:car_id" json:"car_id"`
	TrendType string         `gorm:"column:trend_type;not null" json:"trend_type"`
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName Trend's table name
func (*Trend) TableName() string {
	return TableNameTrend
}
