// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTripOrder = "trip_orders"

// TripOrder mapped from table <trip_orders>
type TripOrder struct {
	ID         int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     string         `gorm:"column:user_id" json:"user_id"`
	CarID      int32          `gorm:"column:car_id" json:"car_id"`
	StartPoint string         `gorm:"column:start_point;not null" json:"start_point"`
	EndPoint   string         `gorm:"column:end_point;not null" json:"end_point"`
	StartTime  time.Time      `gorm:"column:start_time;not null" json:"start_time"`
	EndTime    time.Time      `gorm:"column:end_time;not null" json:"end_time"`
	Price      int32          `gorm:"column:price;not null" json:"price"`
	Status     int16          `gorm:"column:status" json:"status"`
	CreatedAt  time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName TripOrder's table name
func (*TripOrder) TableName() string {
	return TableNameTripOrder
}
