// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID            string         `gorm:"column:id;primaryKey;default:uuid_generate_v4()" json:"id"`
	Username      string         `gorm:"column:username;not null" json:"username"`
	Gender        int16          `gorm:"column:gender" json:"gender"`
	Password      string         `gorm:"column:password;not null" json:"password"`
	Phone         string         `gorm:"column:phone" json:"phone"`
	Birthday      time.Time      `gorm:"column:birthday" json:"birthday"`
	Avatar        string         `gorm:"column:avatar" json:"avatar"`
	OauthID       string         `gorm:"column:oauth_id" json:"oauth_id"`
	OauthProvider string         `gorm:"column:oauth_provider" json:"oauth_provider"`
	Email         string         `gorm:"column:email;not null" json:"email"`
	IntroduceCode string         `gorm:"column:introduce_code" json:"introduce_code"`
	RoleID        int32          `gorm:"column:role_id" json:"role_id"`
	PermissionID  int32          `gorm:"column:permission_id" json:"permission_id"`
	CreatedAt     time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
