// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWishlist = "wishlists"

// Wishlist mapped from table <wishlists>
type Wishlist struct {
	UserID string `gorm:"column:user_id;primaryKey" json:"user_id"`
	CarID  int32  `gorm:"column:car_id;primaryKey" json:"car_id"`
}

// TableName Wishlist's table name
func (*Wishlist) TableName() string {
	return TableNameWishlist
}
