// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"gorm.io/gorm"
	"server-book-ecommerce-gin/internal/controller"
	"server-book-ecommerce-gin/internal/repository"
	"server-book-ecommerce-gin/internal/service"
)

// Injectors from user.wire.go:

func InitUserControllerHandler(db *gorm.DB) (*controller.UserController, error) {
	iUserRepository := repository.NewUserRepository(db)
	iUserService := service.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
