// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"server-car-rental-ecommerce-gin/internal/controller"
	"server-car-rental-ecommerce-gin/internal/repository"
	"server-car-rental-ecommerce-gin/internal/service"
)

// Injectors from user.wire.go:

func InitUserControllerHandler() (*controller.UserController, error) {
	iUserRepository := repository.NewUserRepository()
	iUserService := service.NewUserService(iUserRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
