package constant

const (
	RoleTable               = "roles"
	UserTable               = "users"
	CartItemTable           = "cart_items"
	AddressTable            = "address"
	CategoryTable           = "categories"
	FagTable                = "faqs"
	ImageTable              = "images"
	InvalidateTokenTable    = "invalidated_tokens"
	OrderItemTable          = "order_items"
	OrderTable              = "orders"
	PolicyTable             = "policies"
	ProductTable            = "products"
	PromotionOrderItemTable = "promotion_order_items"
	PromotionOrderTable     = "promotion_orders"
	PromotionTable          = "promotions"
	RefreshTokenTable       = "refresh_tokens"
	ReviewTable             = "reviews"
	RoomProductTable        = "room_products"
	RoomTable               = "rooms"
	SupplierTable           = "suppliers"
	SupportCustomerTable    = "support_customers"
	UserLogTable            = "user_logs"
	WishlistTable           = "wishlists"
)
